# Generated by Django 2.2.5 on 2019-11-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_user',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video_user',
            name='video_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='address',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
