# Generated by Django 2.2.5 on 2019-11-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20191125_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_user',
            name='test',
            field=models.ManyToManyField(to='video.Classification'),
        ),
    ]
