# Generated by Django 2.2.5 on 2019-11-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_user',
            name='test',
        ),
    ]
