# Generated by Django 2.2.5 on 2019-11-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_choice'),
        ('video', '0006_remove_video_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='classification',
        ),
        migrations.AddField(
            model_name='video',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Class'),
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
