# Generated by Django 2.2.5 on 2019-11-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20191126_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='level',
            field=models.CharField(blank=True, choices=[('0', 'low'), ('1', 'high')], max_length=1, null=True),
        ),
    ]
