# Generated by Django 2.2.5 on 2019-11-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
